# Pre-commit plugins https://pre-commit.com/#plugins
# Supported hooks https://pre-commit.com/hooks.html

fail_fast: true
repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff check
        entry: ruff check
        language:  python
        types_or: [python, pyi, jupyter]

    -   id: ruff
        name: ruff format
        entry: ruff format
        language:  python
        types_or: [python, pyi, jupyter]

    # -   id: commit-msg
    #     stages:
    #       - prepare-commit-msg
    #     name: check commit message
    #     entry: python hooks/commit-msg.py
    #     language: system
    #     verbose: true